export const sampleCars = [
  {
    carId: -1,
    userLabel: "E30 M3",
    year: 1988,
    make: "BMW",
    model: "M3",
    color: "red",
    vin: "123456789",
    licensePlate: "ABC123",
    notes: "purchased for $50,000 in 2018",
    // userId: -1,
  },
  {
    carId: -2,
    userLabel: "custom label",
    year: 1993,
    make: "Mazda",
    model: "RX-7",
    color: "optional",
    vin: "optional",
    licensePlate: "optional",
    notes: "Put anything you want here. Maybe purchase info, last oil change, etc.",
    // userId: -1,
  },
  {
    carId: -3,
    userLabel: "mustang",
    year: 2008,
    make: "Ford",
    model: "Mustang",
    color: "",
    vin: "",
    licensePlate: "",
    notes: "",
    // userId: -1,
  },
]
